apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  jwt-secret-key: cGxhY2Vob2xkZXItand0LXNlY3JldC1rZXktbWluLTE2LWNoYXJz
  jwt-refresh-secret-key: cGxhY2Vob2xkZXItand0LXJlZnJlc2gtc2VjcmV0LWtleS1taW4tMTY=
  sendgrid-api-key: UEhBQ0VIT0xERVItU0VOREdSSUQtQVBJLUtFWQ==
