apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongodb-deployment.yaml
  - mongodb-service.yaml
  - app-secret.yaml
  - app-deployment.yaml
  - app-service.yaml
  - nginx-configmap.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
