name: Dependabot auto-merge
on:
  workflow_run:
    workflows: ['e2e']
    types:
      - completed

permissions:
  pull-requests: write
  contents: write
  actions: read

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Auto-merge Dependabot PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          PR=$(gh pr list --head "$HEAD_SHA" --state open --json number,author --jq '.[] | select(.author.login=="dependabot[bot]") | .number')
          if [ -z "$PR" ]; then
            echo "No open dependabot PR found for this commit. Exiting."
            exit 0
          fi
          echo "Auto-merging PR #$PR."
          gh pr merge --auto --merge "$PR"
