name: e2e

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master
      - release/*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'docs/**'

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Setup NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: '25'

      - name: Cache Node.js modules
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - run: npm install --registry=https://registry.npmjs.org

      - name: Running mongodb service
        run: |
          docker compose up -d mongodb
          docker ps -a

      - name: Running e2e testing
        run: npm run test:e2e -- --runInBand --forceExit --testTimeout 30000
